// Generated by CoffeeScript 1.6.3
(function() {
  var dsword, fist, katana, lance, magic, spear, sword;

  magic = function(name, healthloss) {
    return alert("your " + name + " caused a loss of " + healthloss + " health");
  };

  sword = function(damage) {
    return alert("Your sword did -" + damage + " Damage");
  };

  spear = function(damage) {
    return alert("Your spear did -" + damage + " Damage");
  };

  lance = function(damage) {
    return alert("Your lance did -" + damage + " Damage");
  };

  dsword = function(damage) {
    return alert("Your dual swords did -" + damage + " Damage");
  };

  katana = function(damage) {
    return alert("Your katana did -" + damage + " Damage");
  };

  fist = function(damage) {
    return alert("Your fists did -" + damage + " Damage");
  };

}).call(this);
