// Generated by CoffeeScript 1.6.3
(function() {
  var character;

  character = function(name, level, species, admin, donor, weapon) {
    alert("Name = " + name);
    alert("Level = " + level);
    alert("Species = " + species);
    if (admin = true) {
      alert("He is an Admin");
    }
    if (donor = true) {
      alert("Thanks");
    }
    weapon = prompt("What is the weapon?");
    return alert("What a shiny " + weapon);
  };

  character = function(name, level, species, admin, donor, weapon) {
    alert("Name = " + name);
    alert("Level = " + level);
    alert("Species = " + species);
    if (admin = true) {
      alert("He is an Admin");
    }
    if (donor = true) {
      alert("Thanks");
    }
    return alert("What a shiny " + weapon);
  };

}).call(this);
