// Generated by CoffeeScript 1.6.3
(function() {
  var monster;

  monster = function(name, strength, health) {
    alert(name);
    if (strength === 1) {
      alert("I'll sqaush you");
    }
    if (strength === 2) {
      alert("I'll kill you");
    }
    if (strength === 3) {
      alert("Suck It");
    }
    if (strength === 4) {
      alert("DIE");
    }
    if (strength === 5) {
      alert("Maybe you will be a worthy opponent");
    }
    if (strength === 6) {
      alert("Your dead meat!");
    }
    if (strength === 7) {
      alert("You make my blood rage");
    }
    if (strength === 8) {
      alert("I hate you");
    }
    if (strength === 9) {
      alert("I'm praticly a god");
    }
    if (strength === 10) {
      alert("Foolish mortal");
    }
    if (health < 50) {
      alert("Your getting there");
    }
    if (health < 10) {
      alert("Kill me!!!");
    }
    if (health === 10000) {
      alert("I snogged Madame De Pampadore");
    }
    if (name === "Simon") {
      alert("The awesome one.");
      alert("Hail");
    }
    if (name === "The Gambler") {
      return alert("Your in the precense of a time lord");
    }
  };

}).call(this);
