// Generated by CoffeeScript 1.6.3
(function() {
  var ask, assign, hello, say, sonicScrewDriver, write;

  say = function(text) {
    return alert(text);
  };

  assign = function(name, data) {
    return name = data;
  };

  hello = function(name) {
    return alert("Hello " + name);
  };

  ask = function(question) {
    ask = prompt(question);
    return alert(ask);
  };

  sonicScrewDriver = function(sound) {
    return alert(sound);
  };

  write = function(text) {
    return document.write(text);
  };

}).call(this);
