// Generated by CoffeeScript 1.6.3
(function() {
  var AofRect, AofTrap, AofTri;

  AofRect = function(b, h) {
    return alert(b * h);
  };

  AofTri = function(b, h) {
    return alert(b * h / 2);
  };

  AofTrap = function(b1, b2, h) {
    return alert((b1 + b2) * h);
  };

}).call(this);
