// Generated by CoffeeScript 1.6.3
(function() {
  var PofRect, PofTrap, PofTri;

  PofRect = function(b, h) {
    return alert(b * 2 + h * 2);
  };

  PofTri = function(b, s1, s2) {
    return alert(b + s1 + s2);
  };

  PofTrap = function(b1, b2, s1, s2) {
    return b1 + b2 + s1 + s2;
  };

}).call(this);
