// Generated by CoffeeScript 1.6.3
(function() {
  var Xenocide, XenocideM, doctor, theGambler, timebox;

  timebox = function(DR, color) {
    alert("Welcome to your Time Box Doctor " + DR);
    return alert("I'm " + color);
  };

  doctor = function(name, gen) {
    return alert("Hello " + DR + "Generation number " + gen);
  };

  XenocideM = function(gen, message) {
    alert("I am Xenocide (genaration " + gen + "the second most awesome Time Lord ever!");
    return alert(message);
  };

  Xenocide = function(gen) {
    var g;
    alert("I am Xenocide (genaration " + gen + "the second most awesome Time Lord ever!");
    alert("Oh! I am also the maker of BrewScript.");
    g = prompt("Do you feel good or bad?");
    if (g === "Good") {
      return alert("Thats swell!");
    } else {
      return alert("That's too bad");
    }
  };

  theGambler = function() {};

}).call(this);
